- name: Emacs Lisp check
  uses: leotaku/elisp-check@v1.0
  with:
    # Emacs Lisp check to execute.
Consult the README for supported checks.

    check: # optional, default is melpa
    # Entry file for Emacs Lisp check.
Basic globbing is supported.

    file: # optional, default is *.el
    # Whether to ignore warnings.

    ignore_warnings: # optional
    # Whether to treat errors as warnings.

    warnings_as_errors: # optional
